export const jobs = [
  {
    id: "frontend-developer",
    title: "Frontend Developer Intern",
    company: "TechNova Solutions",
    location: "Noida",
    category: "Frontend",
    type: "Internship",
    level: "Fresher",
    salary: "₹15,000 - ₹25,000 / month",
    minSalary: 15000,
    postedDays: 1,
    skills: ["HTML", "CSS", "JavaScript", "React"],
    description:
      "We are looking for a Frontend Developer Intern who can build responsive and user-friendly interfaces using modern frontend technologies.",
    responsibilities: [
      "Build responsive UI pages using HTML, CSS, JavaScript, and React.",
      "Convert design requirements into clean frontend components.",
      "Work with APIs and display dynamic data on the frontend.",
      "Fix UI bugs and improve user experience.",
    ],
    requirements: [
      "Good understanding of HTML, CSS, and JavaScript.",
      "Basic knowledge of React components, props, and state.",
      "Understanding of responsive design.",
      "Git and GitHub basics.",
    ],
  },
  {
    id: "mern-stack-intern",
    title: "MERN Stack Developer Intern",
    company: "CodeCraft Labs",
    location: "Remote",
    category: "Full Stack",
    type: "Internship",
    level: "Fresher",
    salary: "₹20,000 - ₹35,000 / month",
    minSalary: 20000,
    postedDays: 2,
    skills: ["React", "Node.js", "Express", "MongoDB", "REST API"],
    description:
      "Join our MERN team to build full-stack web applications with authentication, dashboards, and REST APIs.",
    responsibilities: [
      "Create reusable React components.",
      "Build REST APIs using Node.js and Express.",
      "Work with MongoDB schemas and CRUD operations.",
      "Integrate frontend with backend APIs.",
    ],
    requirements: [
      "Knowledge of React and JavaScript.",
      "Basic understanding of Node.js and Express.",
      "MongoDB CRUD knowledge.",
      "Ability to explain projects clearly.",
    ],
  },
  {
    id: "nextjs-developer",
    title: "React / Next.js Developer",
    company: "ScaleUp Digital",
    location: "Bengaluru",
    category: "Frontend",
    type: "Full-time",
    level: "Entry Level",
    salary: "₹4 LPA - ₹7 LPA",
    minSalary: 400000,
    postedDays: 4,
    skills: ["React", "Next.js", "JavaScript", "SEO", "API Integration"],
    description:
      "We need a React and Next.js developer who can create production-ready frontend applications with SEO-friendly pages.",
    responsibilities: [
      "Build pages using Next.js App Router.",
      "Create reusable UI components.",
      "Implement dynamic routes and metadata.",
      "Optimize frontend performance and SEO.",
    ],
    requirements: [
      "Strong React fundamentals.",
      "Basic understanding of Next.js App Router.",
      "Good JavaScript knowledge.",
      "Experience with API integration.",
    ],
  },
  {
    id: "node-backend-intern",
    title: "Node.js Backend Intern",
    company: "ServerSide Systems",
    location: "Hyderabad",
    category: "Backend",
    type: "Internship",
    level: "Fresher",
    salary: "₹18,000 - ₹30,000 / month",
    minSalary: 18000,
    postedDays: 6,
    skills: ["Node.js", "Express", "MongoDB", "JWT", "API"],
    description:
      "Backend internship role focused on building REST APIs, authentication systems, and database integration.",
    responsibilities: [
      "Build Express.js routes and controllers.",
      "Create authentication using JWT.",
      "Work with MongoDB and Mongoose.",
      "Handle API errors and validations.",
    ],
    requirements: [
      "Basic Node.js and Express knowledge.",
      "Understanding of REST API.",
      "Knowledge of MongoDB CRUD.",
      "Basic authentication understanding.",
    ],
  },
  {
    id: "fullstack-trainee",
    title: "Full Stack Developer Trainee",
    company: "BrightApps Pvt Ltd",
    location: "Gurugram",
    category: "Full Stack",
    type: "Full-time",
    level: "Entry Level",
    salary: "₹3 LPA - ₹5 LPA",
    minSalary: 300000,
    postedDays: 3,
    skills: ["JavaScript", "React", "Node.js", "SQL", "Git"],
    description:
      "This trainee role is for candidates who want to grow as full-stack developers and work on real client projects.",
    responsibilities: [
      "Develop frontend screens using React.",
      "Work on backend APIs.",
      "Write SQL queries for reports.",
      "Collaborate with team members using Git.",
    ],
    requirements: [
      "Good JavaScript fundamentals.",
      "Basic React knowledge.",
      "SQL basics.",
      "Willingness to learn full-stack development.",
    ],
  },
  {
    id: "ui-developer",
    title: "UI Developer",
    company: "PixelPerfect Studio",
    location: "Pune",
    category: "Frontend",
    type: "Full-time",
    level: "Entry Level",
    salary: "₹3.5 LPA - ₹6 LPA",
    minSalary: 350000,
    postedDays: 5,
    skills: ["HTML", "CSS", "JavaScript", "Responsive Design", "Figma"],
    description:
      "UI Developer role for candidates who can create clean, responsive, and pixel-perfect web interfaces.",
    responsibilities: [
      "Create responsive layouts from Figma designs.",
      "Write clean HTML and CSS.",
      "Add JavaScript interactions.",
      "Improve UI consistency across pages.",
    ],
    requirements: [
      "Strong HTML and CSS.",
      "Responsive design knowledge.",
      "Basic JavaScript.",
      "Eye for clean UI design.",
    ],
  },
];

export function getJobById(id) {
  return jobs.find((job) => job.id === id);
}